version: '3.9'

# In /fullstack/ directory

services:
  backend:
    build:
      context: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend/core:/backend
    command: python manage.py runserver 0.0.0.0:8000