version: '3.9'

# In /fullstack/ directory

services:
  backend:
    build:
      context: ./backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend/core:/backend
    command: > 
      sh -c "python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=pgdatabase
      - DB_NAME=taskdb
      - DB_USER=devuser
      - DB_PASSWORD=StrongPassword+1234
    depends_on:
      - pgdatabase

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    #stdin_open: true
    #tty: true
    depends_on:
      - backend

  pgdatabase:
    image: postgres:14.5-alpine3.16
    volumes:
      # Create named Volume to persist forever
      - task-list-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=StrongPassword+1234

volumes:
  task-list-pgdata: